# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 19) do

  create_table "aplicacions", :force => true do |t|
    t.column "nombre", :string, :limit => 20, :default => "", :null => false
  end

  create_table "categorias", :force => true do |t|
    t.column "categoria", :string, :limit => 25, :default => "", :null => false
  end

  create_table "chats", :force => true do |t|
    t.column "fechaHoraInicio", :datetime, :null => false
    t.column "ultMensaje",      :time,     :null => false
  end

  create_table "consultas", :force => true do |t|
    t.column "fecha",         :date,                  :default => '2008-06-26', :null => false
    t.column "estado_id",     :integer,                                         :null => false
    t.column "titulo",        :string,  :limit => 25, :default => "",           :null => false
    t.column "usuario_id",    :integer,                                         :null => false
    t.column "aplicacion_id", :integer,                                         :null => false
    t.column "categoria_id",  :integer,                                         :null => false
  end

  create_table "estados", :force => true do |t|
    t.column "estado", :string, :null => false
  end

  create_table "eventos", :force => true do |t|
    t.column "fechaHora", :time,                                 :null => false
    t.column "desc",      :string, :limit => 50, :default => "", :null => false
  end

  create_table "imagens", :force => true do |t|
    t.column "content_type",   :string,  :null => false
    t.column "archivo",        :string,  :null => false
    t.column "datos_binarios", :binary,  :null => false
    t.column "mensaje_id",     :integer
  end

  create_table "infos", :force => true do |t|
    t.column "nombre",         :string, :limit => 30,  :null => false
    t.column "desc",           :string, :limit => 100, :null => false
    t.column "archivo",        :string, :limit => 30,  :null => false
    t.column "datos_binarios", :binary,                :null => false
    t.column "tipo",           :string,                :null => false
  end

  create_table "mensaje_de_chats", :force => true do |t|
    t.column "fechaHora",  :datetime, :default => '2008-06-26 00:00:00', :null => false
    t.column "texto",      :text,                                        :null => false
    t.column "usuario_id", :integer,                                     :null => false
    t.column "chat_id",    :integer,                                     :null => false
  end

  create_table "mensajes", :force => true do |t|
    t.column "fechaHora",   :datetime,               :default => '2008-06-26 00:00:00', :null => false
    t.column "texto",       :text,                                                      :null => false
    t.column "usuario_id",  :integer,                                                   :null => false
    t.column "asunto",      :string,   :limit => 40, :default => "",                    :null => false
    t.column "consulta_id", :integer,                                                   :null => false
  end

  create_table "usuarios", :force => true do |t|
    t.column "nombre",      :string,   :limit => 20, :default => ""
    t.column "apellido",    :string,   :limit => 25, :default => ""
    t.column "nomUsuario",  :string,   :limit => 20, :default => ""
    t.column "contrasenia", :string,   :limit => 32, :default => ""
    t.column "fechaNac",    :date,                                   :null => false
    t.column "privilegio",  :integer,                :default => 0
    t.column "email",       :string,   :limit => 40, :default => "", :null => false
    t.column "direccion",   :string,   :limit => 50, :default => "", :null => false
    t.column "provincia",   :string,   :limit => 20, :default => "", :null => false
    t.column "pais",        :string,   :limit => 20, :default => "", :null => false
    t.column "fechaIng",    :datetime,                               :null => false
  end

end
